services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.98.0
    command:
      - --config=/etc/otel-collector.yaml
    volumes:
      - ./infra/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  tempo:
    image: grafana/tempo:2.4.1
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=error
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml

  mimir:
    image: grafana/mimir:2.12.0
    command:
      - -config.file=/etc/mimir.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./infra/mimir.yaml:/etc/mimir.yaml

  loki:
    image: grafana/loki:3.0.0
    command:
      - -config.file=/etc/loki.yaml
      - -target=all
      - -log.level=error
    volumes:
      - ./infra/loki.yaml:/etc/loki.yaml

  grafana:
    image: grafana/grafana:10.4.2
    volumes:
      - ./infra/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./infra/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./infra/grafana-dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE="traceqlEditor traceToMetrics metricsSummary"
      - GF_LOG_LEVEL=error
    ports:
      - "3000:3000"