apiVersion: 1

datasources:
  - name: Metrics
    type: prometheus
    uid: mimir
    access: proxy
    orgId: 1
    url: http://monitoring_mimir:9009/prometheus
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      prometheusType: Mimir
      prometheusVersion: 2.9.1
      timeInterval: "10s"

  - name: Logs
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://monitoring_loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: trace_id
          matcherType: label
          name: 'Trace ID'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  - name: Traces
    type: tempo
    uid: tempo
    access: proxy
    orgId: 1
    url: http://monitoring_tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    apiVersion: 1
    jsonData:
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: mimir
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: false
        spanStartTimeShift: -10m
        spanEndTimeShift: 10m
        tags: [{ key: 'service.name', value: 'service_name' }] 
        customQuery: true
        query: '{$${__tags}} | trace_id="$${__span.traceId}" | span_id="$${__span.spanId}"'
      tracesToMetrics:
        datasourceUid: mimir

  - name: ClickHouse-official
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: otel
      port: 9000
      server: monitoring_clickhouse
      username: default
      tlsSkipVerify: false
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: '1.2.9'
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: '1.2.9'
        durationUnit: 'seconds'

  - name: ClickHouse-vertamedia
    type: vertamedia-clickhouse-datasource
    url: http://monitoring_clickhouse:8123
