receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 5s
    send_batch_size: 10000

exporters:
  otlp/tempo:
    endpoint: monitoring_tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://monitoring_loki:3100/otlp
    tls:
      insecure: true
  prometheusremotewrite/mimir:
    endpoint: http://monitoring_mimir:9009/api/v1/push
    tls:
      insecure: true
  clickhouse:
    endpoint: tcp://monitoring_clickhouse:9000?dial_timeout=10s&compress=lz4
    database: otel
    ttl: 144h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  telemetry:
    logs:
      level: error
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir, clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, clickhouse]
