name: Localtest PR Analysis

on:
  pull_request:
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
        working-directory: 'src/'
      - name: Build LocalTest
        run: dotnet build --configuration Debug --no-restore
        working-directory: 'src/'
